### ISSUE TITLE
Add lenses

### ISSUE THREAD

**Issue by treeowl** [quchen/binary-typed#40]
I think they probably can look something like the following:

```haskell
-- Corresponds to mapTyped
typedLens :: Typeable b => Lens (Typed a) (Typed b) a b

-- Corresponds to reValue
typedLens' :: Typeable a => Lens' (Typed a) (Typed a)
```

**Comment by quchen** [comment]
I'm not a big fan of providing lenses in the modules themselves, but a `.Lens` submodule might be a good addition.

**Comment by quchen** [comment]
Closing because nobody seems to be interested in building this

**Comment by treeowl** [comment]
I just forgot...
