### ISSUE TITLE
build failure: Data.Typeable does not export mkTyConApp

### ISSUE THREAD

**Issue by DanBurton** [quchen/binary-typed#42]
Build failure with GHC 8.2.1 as seen on the Stackage build server:

```
[1 of 4] Compiling Data.Binary.Typed.Internal ( src/Data/Binary/Typed/Internal.hs, dist/build/Data/Binary/Typed/Internal.o )

src/Data/Binary/Typed/Internal.hs:484:39: error:
    Not in scope: ‘Ty.mkTyConApp’
    Module ‘Data.Typeable’ does not export ‘mkTyConApp’.
    |
484 | unStripTypeRep (TypeRep tyCon args) = Ty.mkTyConApp (unStripTyCon tyCon)
    |                                       ^^^^^^^^^^^^^
```

**Comment by DanBurton** [comment]
Also

```
src/Data/Binary/Typed/Internal.hs:503:30: error:
    Not in scope: ‘Ty.mkTyCon3’
    Module ‘Data.Typeable’ does not export ‘mkTyCon3’.
    |
503 | unStripTyCon (TyCon p m n) = Ty.mkTyCon3 p m n -- package, module, name
    |                              ^^^^^^^^^^^
```

**Comment by quchen** [comment]
Hmm, I wonder how recent these breakages are. Thanks for reporting!

**Comment by hvr** [comment]
@quchen Fyi, I just revised 

 - https://hackage.haskell.org/package/binary-typed-0.1.0.0/revisions/
 - https://hackage.haskell.org/package/binary-typed-0.1.0.1/revisions/
 - https://hackage.haskell.org/package/binary-typed-0.2.0.0/revisions/
 - https://hackage.haskell.org/package/binary-typed-0.2.0.1/revisions/
 - https://hackage.haskell.org/package/binary-typed-0.2.1.0/revisions/
 - https://hackage.haskell.org/package/binary-typed-0.2.2/revisions/
 - https://hackage.haskell.org/package/binary-typed-0.2.3/revisions/
 - https://hackage.haskell.org/package/binary-typed-0.3/revisions/
 - https://hackage.haskell.org/package/binary-typed-1.0/revisions/

As this affected all of `binary-typed` releases; see also https://matrix.hackage.haskell.org/package/binary-typed

**Comment by DanBurton** [comment]
Very recent! They are breakages due to GHC 8.2.1 and `base-4.10.0.0`, which were released about a week ago.

**Comment by quchen** [comment]
Thanks Herbert. 

I'm considering deprecating this whole package, since the new typeable seems to make it impossible to create a Tapeable by hand. That, and nobody seems to use the package (including myself).

**Comment by quchen** [comment]
I deprecated the package. I have no use for it now, and neither does anyone else it seems, so I see no reason to maintain it right now.
